language: node_js
dist: trusty
sudo: required
node_js:
- stable
addons:
  firefox: 46.0
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
    
before_script:
- npm install -g gulp bower web-component-tester
- npm install
- bower install
script:
- gulp
- gulp lint
- xvfb-run wct
#- wct --skip-plugin local